Fix systemd service not starting

diff --git a/rootcopy/bin/wallpaper-cycler b/rootcopy/bin/wallpaper-cycler
--- a/rootcopy/bin/wallpaper-cycler
+++ b/rootcopy/bin/wallpaper-cycler
@@ -31,6 +31,19 @@ if [[ $# -gt 0 ]]; then
 		mkdir -p $WALLPAPERS && $0 enable
 		exit $?
 
+
+	elif [[ " $1 " = " user " ]] ;then
+		if [[ $# -eq 2 ]]; then
+			if [[ -d /home/$2 ]]; then
+				/bin/bash HOME=/home/$2 USER=$2 $0 cycle
+			else
+				echo "Could not find home directory for user"
+				exit 2
+		else
+			echo "No valid user set"
+			exit 1
+		fi
+
 	# Set wallpaper directory
 	elif [[ " $1 " = " path " ]] ;then
 		if [[ $# -eq 2 ]]; then
